// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py


namespace KSPCompiler.Domain.Ast.Blocks
{
    /// <summary>
    /// AST node representing an user Defined Functions (KSP)
    /// </summary>
    public partial class AstUserFunctionDeclaration : AstFunctionalSyntaxNode
    {
        /// <summary>
        /// Ctor
        /// </summary>
        public AstUserFunctionDeclaration( IAstNode parent )
            : base( AstNodeId.UserFunctionDeclaration, parent )
        {}
    }
}