// Generated by CodeGenerators/ASTCodeGenerator

namespace KSPCompiler.Domain.Ast.Blocks
{
    /// <summary>
    /// AST node representing an argument
    /// </summary>
    public partial class AstArgument : AstNode, INameable
    {

        /// <summary>
        /// Ctor
        /// </summary>
        public AstArgument( IAstNode parent )
            : base( AstNodeId.Argument, parent )
        {}

        #region INameable
        ///
        /// <inheritdoc/>
        ///
        public string Name { get; set; } = "";
        #endregion INameable

        #region IAstNodeAcceptor

        ///
        /// <inheritdoc/>
        ///
        public override T Accept<T>( IAstVisitor<T> visitor )
        {
            return visitor.Visit( this );
        }

        ///
        /// <inheritdoc/>
        ///
        public override void AcceptChildren<T>( IAstVisitor<T> visitor )
        {}

        #endregion IAstNodeAcceptor
    }
}
