// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py


namespace KSPCompiler.Domain.Ast.Blocks
{
    /// <summary>
    /// AST node representing a callback, block in function
    /// </summary>
    public partial class AstBlock : AstNode
    {
        /// <summary>
        /// Ctor
        /// </summary>
        public AstBlock( IAstNode parent )
            : base( AstNodeId.Block, parent )
        {
            Initialize();
        }

        private partial void Initialize();

        #region Part of IAstNodeAcceptor
        ///
        /// <inheritdoc/>
        ///
        public override T Accept<T>( IAstVisitor<T> visitor )
        {
            return visitor.Visit( this );
        }
        #endregion IAstNodeAcceptor
    }
}