// Generated by CodeGenerators/ASTCodeGenerator

namespace KSPCompiler.Domain.Ast.Blocks
{
    /// <summary>
    /// AST node representing a root node
    /// </summary>
    public partial class AstCompilationUnit : AstNode
    {
        #region Fields
        /// <summary>
        /// public AstNodeList<AstNode> GlobalBlocks { get; }
        /// </summary>
        public AstNodeList<AstNode> GlobalBlocks { get; }

        #endregion Fields

        /// <summary>
        /// Ctor.
        /// </summary>
        public AstCompilationUnit( IAstNode parent )
            : base( AstNodeId.CompilationUnit, parent )
        {
            GlobalBlocks = new AstNodeList<AstNode>( this );
        }


        #region IAstNodeAcceptor

        ///
        /// <inheritdoc/>
        ///
        public override T Accept<T>( IAstVisitor<T> visitor )
        {
            return visitor.Visit( this );
        }

        ///
        /// <inheritdoc/>
        ///
        public override void AcceptChildren<T>( IAstVisitor<T> visitor )
        {
            foreach( var n in GlobalBlocks )
            {
                n.Accept( visitor );
            }
        }

        #endregion IAstNodeAcceptor
    }
}
