// Generated by CodeGenerators/ASTCodeGenerator

namespace KSPCompiler.Domain.Ast.Blocks
{
    /// <summary>
    /// AST node representing a callback definition
    /// </summary>
    public partial class AstCallbackDeclaration : AstFunctionalSyntaxNode
    {
        #region Fields
        /// <summary>
        /// public AstArgumentList ArgumentList { get; }
        /// </summary>
        public AstArgumentList ArgumentList { get; }

        /// <summary>
        /// public virtual bool HasArgument => ArgumentList.HasArgument;
        /// </summary>
        public virtual bool HasArgument => ArgumentList.HasArgument;

        /// <summary>
        /// public virtual int ArgumentCount => HasArgument ? ArgumentList.Arguments.Count : 0;
        /// </summary>
        public virtual int ArgumentCount => HasArgument ? ArgumentList.Arguments.Count : 0;

        #endregion Fields

        /// <summary>
        /// Ctor.
        /// </summary>
        public AstCallbackDeclaration( IAstNode parent )
            : base( AstNodeId.CallbackDeclaration, parent )
        {
            ArgumentList = new AstArgumentList( this );
        }

    }
}
