// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Blocks
{
    /// <summary>
    /// AST node representing a root node
    /// </summary>
    public partial class AstCompilationUnit
    {
    }
}