<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>default</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>KSPCompiler.Shared.IO.Symbols.Yaml.Tests</RootNamespace>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="nunit" Version="4.5.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared.IO.Local\Shared.IO.Local.csproj" />
      <ProjectReference Include="..\Shared.IO.Symbols.Mock\Shared.IO.Symbols.Mock.csproj" />
      <ProjectReference Include="..\Shared.IO.Symbols.Yaml\Shared.IO.Symbols.Yaml.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="TestData\**\*">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
