// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Node.Statements
{
    /// <summary>
    /// AST node representing a primitive variable initialization
    /// </summary>
    public class AstPrimitiveInititalizer
    {
    }
}