// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Node.Statements
{
    /// <summary>
    /// AST node representing a while statement
    /// </summary>
    public class AstWhileStatement
    {
    }
}