// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Expressions
{
    /// <summary>
    /// AST node representing an integer literal
    /// </summary>
    public partial class AstIntLiteral
    {
    }
}