// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Expressions
{
    /// <summary>
    /// AST node representing a string literal
    /// </summary>
    public partial class AstStringLiteral
    {
    }
}