// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Expressions
{
    /// <summary>
    /// AST node representing a comma-separated list of expressions (including assignment expressions)
    /// </summary>
    public partial class AstAssignmentExpressionList
    {
    }
}