// Generated by CodeGenerators/ASTCodeGenerator

namespace KSPCompiler.Domain.Ast.Expressions
{
    /// <summary>
    /// AST node representing an assignment (:=)
    /// </summary>
    public partial class AstAssignmentExpression : AstExpressionSyntaxNode
    {
        #region Fields
        /// <summary>
        /// Operator type for assigning
        /// </summary>
        public OperatorType Operator { get; set; } = OperatorType.Assign;

        #endregion Fields

        /// <summary>
        /// Ctor.
        /// </summary>
        public AstAssignmentExpression(
            IAstNode parent,
            AstExpressionSyntaxNode left,
            AstExpressionSyntaxNode right )
            : base( AstNodeId.AssignmentExpression, parent, left, right )
        {}

        public AstAssignmentExpression(
            AstExpressionSyntaxNode left,
            AstExpressionSyntaxNode right )
            : base( AstNodeId.AssignmentExpression, IAstNode.None, left, right )
        {}


        #region InnerEnums
    
        public enum OperatorType
        {
            /// <summary>
            /// :=
            /// </summary>
            Assign
    
        }
    
        #endregion InnerEnums
    }
}
