// Generated by CodeGenerators/ASTCodeGenerator

using KSPCompiler.Domain.Ast.Attributes;

namespace KSPCompiler.Domain.Ast.Expressions
{
    /// <summary>
    /// AST node representing a comma-separated list of expressions (including assignment expressions)
    /// </summary>
    [ExtendedSyntax]
    public partial class AstAssignmentExpressionList : AstNode
    {
        #region Fields
        /// <summary>
        /// expression list
        /// </summary>
        public AstNodeList<AstAssignmentExpression> Expressions { get; }

        #endregion Fields

        /// <summary>
        /// Ctor.
        /// </summary>
        public AstAssignmentExpressionList( IAstNode parent )
            : base( AstNodeId.AssignmentExpressionList, parent )
        {
            Expressions = new AstNodeList<AstAssignmentExpression>( this );
        }


        #region IAstNodeAcceptor

        ///
        /// <inheritdoc/>
        ///
        public override T Accept<T>( IAstVisitor<T> visitor )
        {
            return visitor.Visit( this );
        }

        ///
        /// <inheritdoc/>
        ///
        public override void AcceptChildren<T>( IAstVisitor<T> visitor )
        {
            foreach( var n in Expressions )
            {
                n.Accept( visitor );
            }
        }

        #endregion IAstNodeAcceptor
    }
}
