// Generated by CodeGenerators/ASTCodeGenerator

namespace KSPCompiler.Domain.Ast.Expressions
{
    /// <summary>
    /// AST node representing a comma-separated list of expressions
    /// </summary>
    public partial class AstExpressionList : AstExpressionSyntaxNode
    {
        #region Fields
        /// <summary>
        /// expression list
        /// </summary>
        public AstNodeList<AstExpressionSyntaxNode> Expressions { get; }

        #endregion Fields

        /// <summary>
        /// Ctor.
        /// </summary>
        public AstExpressionList( IAstNode parent )
            : base( AstNodeId.ExpressionList, parent )
        {
            Expressions = new AstNodeList<AstExpressionSyntaxNode>( this );
        }


        #region IAstNodeAcceptor

        ///
        /// <inheritdoc/>
        ///
        public override void AcceptChildren<T>( IAstVisitor<T> visitor )
        {
            foreach( var n in Expressions )
            {
                n.Accept( visitor );
            }
        }

        #endregion IAstNodeAcceptor
    }
}
