// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Expressions
{
    /// <summary>
    /// AST node representing a comparison operator: greater than (>)
    /// </summary>
    public partial class AstGreaterThanExpression
    {
    }
}