// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Expressions
{
    /// <summary>
    /// Ast node representing a modulo operator (%)
    /// </summary>
    public partial class AstModuloExpression : AstExpressionSyntaxNode
    {
        /// <summary>
        /// Ctor
        /// </summary>
        public AstModuloExpression(
            IAstNode parent,
            AstExpressionSyntaxNode left,
            AstExpressionSyntaxNode right )
            : base(
                AstNodeId.ModuloExpression,
                parent,
                left, right )
        {}

        /// <summary>
        /// Ctor
        /// </summary>
        public AstModuloExpression(
            AstExpressionSyntaxNode left,
            AstExpressionSyntaxNode right )
            : base(
                AstNodeId.ModuloExpression,
                IAstNode.None,
                left, right )
        {}

        /// <summary>
        /// Ctor
        /// </summary>
        public AstModuloExpression()
            : base(
                AstNodeId.ModuloExpression,
                IAstNode.None,
                AstExpressionSyntaxNode.None,
                AstExpressionSyntaxNode.None )
        {}
    }
}