// Generated by CodeGenerators/ASTCodeGenerator

namespace KSPCompiler.Domain.Ast.Expressions
{
    /// <summary>
    /// AST node representing a symbolic reference
    /// </summary>
    public partial class AstSymbolExpression : AstExpressionSyntaxNode, INameable
    {

        /// <summary>
        /// Ctor
        /// </summary>
        public AstSymbolExpression( IAstNode parent )
            : base( AstNodeId.SymbolExpression, parent )
        {}

        #region INameable
        ///
        /// <inheritdoc/>
        ///
        public string Name { get; set; } = "";
        #endregion INameable
    }
}
