// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Expressions
{
    /// <summary>
    /// AST node representing a symbolic reference
    /// </summary>
    public partial class AstSymbolExpression
    {
    }
}