// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Node.Expressions
{
    /// <summary>
    /// AST node representing an array element reference expression ( Left: ASTSymbolExpression, Right: ASTExpressionSyntaxNode )
    /// </summary>
    public class AstArrayElementExpression
    {
    }
}