// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Node.Expressions
{
    /// <summary>
    /// AST node representing an invoking the KSP command
    /// </summary>
    public class AstCallExpression
    {
    }
}