// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Node.Expressions
{
    /// <summary>
    /// AST node representing a comparison operator: equal
    /// </summary>
    public class AstEqualExpression
    {
    }
}