// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Node.Expressions
{
    /// <summary>
    /// AST node representing a comparison operator: less equal (&lt;=)
    /// </summary>
    public class AstLessEqualExpression
    {
    }
}