// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Node.Expressions
{
    /// <summary>
    /// AST node representing a modulo operator (%)
    /// </summary>
    public class AstModuloExpression
    {
    }
}