// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Node.Expressions
{
    /// <summary>
    /// AST node representing an assignment (*=)
    /// </summary>
    public class AstMultiplyingAssignmentExpression
    {
    }
}