// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Node.Expressions
{
    /// <summary>
    /// AST node representing a subtraction operator (-)
    /// </summary>
    public class AstSubtractionExpression
    {
    }
}