<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <LangVersion>default</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <Copyright>R-Koubou</Copyright>
        <Company>R-Koubou</Company>
        <Product>KSPCompiler.Shared</Product>
        <AssemblyName>KSPCompiler.Shared</AssemblyName>
        <RootNamespace>KSPCompiler.Shared</RootNamespace>
    </PropertyGroup>

</Project>
