// Generated by CodeGenerators/ASTCodeGenerator

namespace KSPCompiler.Domain.Ast
{
    public enum AstNodeId
    {
        None,
        CompilationUnit, 
        CallbackDeclaration, 
        UserFunctionDeclaration, 
        Argument, 
        ArgumentList, 
        Block, 
        CaseBlock, 
        VariableDeclaration, 
        VariableInitializer, 
        PrimitiveInitializer, 
        ArrayInitializer, 
        IfStatement, 
        WhileStatement, 
        SelectStatement, 
        CallKspUserFunctionStatement, 
        KspPreprocessorDefine, 
        KspPreprocessorUndefine, 
        KspPreprocessorIfdefine, 
        KspPreprocessorIfnotDefine, 
        SymbolExpression, 
        ExpressionList, 
        AssignmentExpression, 
        AssignmentExpressionList, 
        AstExpressionList

    }
}
