// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast
{
    /// <summary>
    /// The Empty Ast Object
    /// </summary>
    public partial class AstNone : AstNode
    {
    }
}