// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py

using KSPCompiler.Domain.Ast.Blocks;

namespace KSPCompiler.Domain.Ast
{
    public interface IAstVisitor<out T>
    {
        public T Visit( AstCompilationUnit node );
        public T Visit( AstCallbackDeclaration node );
        public T Visit( AstUserFunctionDeclaration node );
        public T Visit( AstArgument node );
        public T Visit( AstArgumentList node );
        public T Visit( AstBlock node );
        public T Visit( AstCaseBlock node );
        T Visit( IAstNode node )
        {
            return Visit( (dynamic)node );
        }
    }
}
