// Generated by CodeGenerators/ASTCodeGenerator

namespace KSPCompiler.Domain.Ast.Statements
{
    /// <summary>
    /// AST node representing a call statement
    /// </summary>
    public partial class AstCallKspUserFunctionStatement : AstStatementSyntaxNode, INameable
    {

        /// <summary>
        /// Ctor
        /// </summary>
        public AstCallKspUserFunctionStatement( IAstNode parent )
            : base( AstNodeId.CallKspUserFunctionStatement, parent )
        {}

        #region INameable
        ///
        /// <inheritdoc/>
        ///
        public string Name { get; set; } = "";
        #endregion INameable

        #region IAstNodeAcceptor

        ///
        /// <inheritdoc/>
        ///
        public override void AcceptChildren<T>( IAstVisitor<T> visitor )
        {
            throw new System.NotImplementedException();
        }

        #endregion IAstNodeAcceptor
    }
}
