// Generated by CodeGenerators/ASTCodeGenerator
using KSPCompiler.Domain.Ast.Blocks;

namespace KSPCompiler.Domain.Ast.Statements
{
    /// <summary>
    /// AST node representing an if statement
    /// </summary>
    public partial class AstIfStatement : AstConditionalStatement
    {
        #region Fields
        /// <summary>
        /// The code block when if condition is not satisfied
        /// </summary>
        public AstBlock? ElseBlock { get; set; }

        #endregion Fields

        /// <summary>
        /// Ctor.
        /// </summary>
        public AstIfStatement() : this( IAstNode.None ) {}

        /// <summary>
        /// Ctor.
        /// </summary>
        public AstIfStatement( IAstNode parent )
            : base( AstNodeId.IfStatement, parent ) {}

    }
}
