// Generated by CodeGenerators/ASTCodeGenerator
using KSPCompiler.Domain.Ast.Expressions;

namespace KSPCompiler.Domain.Ast.Statements
{
    /// <summary>
    /// AST node representing a KSP Preprocessor - SET_CONDITION
    /// </summary>
    public partial class AstKspPreprocessorDefine : AstStatementSyntaxNode
    {
        #region Fields
        /// <summary>
        /// Preprocessor symbol
        /// </summary>
        public AstSymbolExpression Symbol { get; }

        #endregion Fields

        /// <summary>
        /// Ctor.
        /// </summary>
        public AstKspPreprocessorDefine( IAstNode parent )
            : base( AstNodeId.KspPreprocessorDefine, parent )
        {
            Symbol = new AstSymbolExpression( this );
        }


        #region IAstNodeAcceptor

        ///
        /// <inheritdoc/>
        ///
        public override void AcceptChildren<T>( IAstVisitor<T> visitor )
        {
            throw new System.NotImplementedException();
        }

        #endregion IAstNodeAcceptor
    }
}
