// Generated by CodeGenerators/ASTCodeGenerator
using KSPCompiler.Domain.Ast.Expressions;

namespace KSPCompiler.Domain.Ast.Statements
{
    /// <summary>
    /// AST node representing a primitive variable initialization
    /// </summary>
    public partial class AstPrimitiveInitializer : AstStatementSyntaxNode
    {
        #region Fields
        /// <summary>
        /// Assignment expression
        /// </summary>
        public AstExpressionSyntaxNode? Expression { get; }

        /// <summary>
        /// Assignment multiple expression (ui_type, constructor)
        /// </summary>
        public AstExpressionList? ExpressionList { get; }

        #endregion Fields

        /// <summary>
        /// Ctor.
        /// </summary>
        public AstPrimitiveInitializer(
            IAstNode parent,
            AstExpressionSyntaxNode? expression = null,
            AstExpressionList? expressionList = null )
            : base( AstNodeId.PrimitiveInitializer, parent )
        {
            Expression     = expression;
            ExpressionList = expressionList;
        }


        #region IAstNodeAcceptor

        ///
        /// <inheritdoc/>
        ///
        public override void AcceptChildren<T>( IAstVisitor<T> visitor )
        {
            throw new System.NotImplementedException();
        }

        #endregion IAstNodeAcceptor
    }
}
