// Generated by CodeGenerators/ASTCodeGenerator

namespace KSPCompiler.Domain.Ast.Statements
{
    /// <summary>
    /// AST node representing a variable initialization
    /// </summary>
    public partial class AstVariableInitializer : AstNode
    {
        #region Fields
        /// <summary>
        /// public AstPrimitiveInitializer? PrimitiveInitializer { get; set; }
        /// </summary>
        public AstPrimitiveInitializer? PrimitiveInitializer { get; set; }

        /// <summary>
        /// public AstArrayInitializer? ArrayInitializer { get; set; }
        /// </summary>
        public AstArrayInitializer? ArrayInitializer { get; set; }

        #endregion Fields

        /// <summary>
        /// Ctor
        /// </summary>
        public AstVariableInitializer( IAstNode parent )
            : base( AstNodeId.VariableInitializer, parent )
        {}

        #region IAstNodeAcceptor

        ///
        /// <inheritdoc/>
        ///
        public override T Accept<T>( IAstVisitor<T> visitor )
        {
            return visitor.Visit( this );
        }

        ///
        /// <inheritdoc/>
        ///
        public override void AcceptChildren<T>( IAstVisitor<T> visitor )
        {
            PrimitiveInitializer?.AcceptChildren( visitor );
            ArrayInitializer?.AcceptChildren( visitor );
        }

        #endregion IAstNodeAcceptor
    }
}
