// Generated by CodeGenerators/ASTCodeGenerator/ast_gen.py
namespace KSPCompiler.Domain.Ast.Statements
{
    /// <summary>
    /// AST node representing a while statement
    /// </summary>
    public partial class AstWhileStatement
    {
    }
}