// Generated by CodeGenerators/ASTCodeGenerator

namespace KSPCompiler.Domain.Ast.Statements
{
    /// <summary>
    /// AST node representing a while statement
    /// </summary>
    public partial class AstWhileStatement : AstConditionalStatement
    {

        /// <summary>
        /// Ctor.
        /// </summary>
        public AstWhileStatement() : this( null ) {}

        /// <summary>
        /// Ctor.
        /// </summary>
        public AstWhileStatement( IAstNode parent )
            : base( AstNodeId.WhileStatement, parent ) {}

    }
}
