name: Build Language Server (rc)

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - release/**

  workflow_dispatch:

jobs:
  build-language-server-rc:
    uses: ./.github/workflows/build_csproj.yml
    secrets: inherit
    with:
      channel: rc
      prefix: KSP-LanguageServer
      base_dir: "Compiler/Features/LanguageServer/Applications/LanguageServerFramework"
      csproject_filename: "LSServer.LanguageServerFramework.csproj"
