name: Build KSP Compiler CLI

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: ""
        description: |
          This Language Server version to set (e.g.: 1.2.3).
      channel:
        required: true
        type: string
        default: "develop"
        description: |
          Build channel (develop, rc, release)

  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
        default: ""
        description: |
          This Language Server version to set (e.g.: 1.2.3).
      channel:
        required: true
        type: choice
        options:
          - develop
          - rc
          - release
        description: |
          Build channel (develop, rc, release)

jobs:
  #--------------------------------------------------------------
  # Build Compiler CLI
  #--------------------------------------------------------------
  build:
    name: build (${{ matrix.build_configuration }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_configuration: [Debug, Release]
    env:
      DOTNET_SDK_VERSION: '10.*'
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      PREFIX: KSPCompiler
      BASE_DIR: Compiler/Features/Compilation/Applications/Compilation.Cli
      PUBLISH_DIRNAME: publish
      BUILD_CONFIGURATION: ${{ matrix.build_configuration }}

    steps:
    - name: Show workflow inputs
      run: |
        {
          echo "## Workflow Inputs"
          echo ""
          echo "|name|value|"
          echo "|----|-----|"
          echo "|ref| ${{ github.ref }}|"
          echo "|Commit SHA| ${{ github.sha }}|"
          echo "|version|${{ inputs.version }}|"
          echo "|channel|${{ inputs.channel }}|"
          echo ""
        } >> $GITHUB_STEP_SUMMARY

    #----------------------------------------------------------
    # Guard - tag build must be release channel
    #----------------------------------------------------------
    - name: Guard - tag build must be release channel
      if: ${{ inputs.channel == 'release' && !startsWith(github.ref, 'refs/tags/v') }}
      run: |
        echo "::error::Must use channel=release when building from tag/v*"
        exit 1

    #----------------------------------------------------------
    # Setup Environment Variables
    #----------------------------------------------------------
    - name: Setup Branch Name Variable
      run: echo "BRANCH_NAME=$(echo ${{ github.ref_name }} | sed 's|/|-|g')" >> $GITHUB_ENV

    - name: Setup Publish Directory Variable
      run: |
        echo "PUBLISH_DIR=${{ env.BASE_DIR }}/${{ env.PUBLISH_DIRNAME }}" >> $GITHUB_ENV
        echo "PUBLISH_RELATIVE_DIR_FROM_BASE=${{ env.PUBLISH_DIRNAME }}" >> $GITHUB_ENV

    - name: Setup Version Variable
      run: |
        echo "BUILD_VERSION=${{ (inputs.version != '' && inputs.version) || '0.0.0' }}" >> $GITHUB_ENV

    - name: Setup Version Information Path Variable
      run: |
        echo "VERSION_INFO_PATH=${{ env.PUBLISH_DIR }}/VERSION.txt" >> $GITHUB_ENV

    #----------------------------------------------------------
    # Checkout
    #----------------------------------------------------------
    - name: Checkout
      uses: actions/checkout@v4

    #----------------------------------------------------------
    # Setup .NET SDK
    #----------------------------------------------------------
    - name: Install SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

    #----------------------------------------------------------
    # Build
    #----------------------------------------------------------
    - name: Build for dotnet (with version info)
      run: |
        pushd ${{ env.BASE_DIR }}
        dotnet publish -p:Version=${{ env.BUILD_VERSION }} -p:AssemblyVersion=${{ env.BUILD_VERSION }} -c ${{ env.BUILD_CONFIGURATION }} -o ${{ env.PUBLISH_RELATIVE_DIR_FROM_BASE }}
        popd

    #----------------------------------------------------------
    # Create Version Information File
    #----------------------------------------------------------
    - name: Create Version information file
      run: |
        mkdir -p ${{ env.PUBLISH_DIR }}
        echo "Version: ${{ env.BUILD_VERSION }}" > ${{ env.VERSION_INFO_PATH }}
        echo "Build date: $(date)" >> ${{ env.VERSION_INFO_PATH }}
        echo "Branch: ${{ github.ref_name }}" >> ${{ env.VERSION_INFO_PATH }}
        echo "Commit: ${{ github.sha }}" >> ${{ env.VERSION_INFO_PATH }}
        echo "Build configuration: ${{ env.BUILD_CONFIGURATION }}" >> ${{ env.VERSION_INFO_PATH }}

    #----------------------------------------------------------
    # Create Artifact
    #----------------------------------------------------------
    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PREFIX }}-${{ env.BUILD_CONFIGURATION }}-v${{ env.BUILD_VERSION }}
        path: ${{ env.BASE_DIR }}/${{ env.PUBLISH_DIRNAME }}
