name: Build LSP Server (Embedded)

env:
  DOTNET_SDK_VERSION: '9.0.*'
  PREFIX: KSP-LSP-Server-Embedded
on:
  workflow_call:
    inputs:
      build-configuration:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      build-configuration:
        description: "Build configuration for msbuild"
        required: true
        type: choice
        options:
          - Debug
          - Release

jobs:
  #--------------------------------------------------------------
  # Build LSP Server
  #--------------------------------------------------------------
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      BASE_DIR: ${{ github.workspace }}/Compiler/Applications/LSP/LSPServer.Embedded
      PUBLISH_DIR: publish/embedded

    steps:
    - name: Show workflow inputs
      run: |
        echo ${{ inputs.build-configuration }}

    - name: Sanitize Branch Name
      run: echo "BRANCH_NAME=$(echo ${{ github.ref_name }} | sed 's|/|-|g')" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4

    #----------------------------------------------------------
    # Setup .NET SDK
    #----------------------------------------------------------
    - name: Install SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

    #----------------------------------------------------------
    # Build LSP Server Embedded
    #----------------------------------------------------------
    - name: Build LSP Server
      run: |
        pushd ${{ env.BASE_DIR }}
        dotnet publish -c ${{ inputs.build-configuration }} -o ${{ env.PUBLISH_DIR }}
        popd

    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PREFIX }}-${{ inputs.build-configuration }}-${{ env.BRANCH_NAME }}
        path: ${{ env.BASE_DIR }}/${{ env.PUBLISH_DIR }}
