name: Build Language Server

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: ""
        description: |
          This Language Server version to set (e.g.: 1.2.3).
      channel:
        required: true
        type: string
        default: "develop"
        description: |
          Build channel (develop, rc, release)

  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string
        default: ""
        description: |
          This Language Server version to set (e.g.: 1.2.3).
      channel:
        required: true
        type: choice
        options:
          - develop
          - rc
          - release
        description: |
          Build channel (develop, rc, release)

#--------------------------------------------------------------
# Build Language Server
#--------------------------------------------------------------
jobs:
  build-language-server:
    name: build (${{ matrix.build_configuration }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_configuration: [Debug, Release]
    env:
      DOTNET_SDK_VERSION: '10.*'
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      PREFIX: KSP-LanguageServer
      CSPROJ_FILENAME: LSServer.LanguageServerFramework.csproj
      BASE_DIR: ${{ github.workspace }}/Compiler/Features/LanguageServer/Applications/LanguageServerFramework
      PUBLISH_DIRNAME: publish
      BUILD_CONFIGURATION: ${{ matrix.build_configuration }}

    steps:
    - name: Show workflow inputs
      run: |
        {
          echo "## Workflow Inputs"
          echo ""
          echo "|name|value|"
          echo "|ref| ${{ github.ref }}|"
          echo "|Commit SHA| ${{ github.sha }}|"
          echo "|version|${{ inputs.version }}|"
          echo "|channel|${{ inputs.channel }}|"
          echo ""
        } >> $GITHUB_STEP_SUMMARY

    #----------------------------------------------------------
    # Guard - tag build must be release channel
    #----------------------------------------------------------
    - name: Guard - tag build must be release channel
      if: ${{ inputs.channel == 'release' && !startsWith(github.ref, 'refs/tags/v') }}
      run: |
        echo "::error::Must use channel=release when building from tag/v*"
        exit 1

    #----------------------------------------------------------
    # Setup Environment Variables
    #----------------------------------------------------------
    - name: Sanitize Branch Name
      run: echo "BRANCH_NAME=$(echo ${{ github.ref_name }} | sed 's|/|-|g')" >> $GITHUB_ENV

    - name:  Setup csproj file path variable
      run: |
        echo "CSPROJ_PATH=${{ env.BASE_DIR }}/${{ env.CSPROJ_FILENAME }}" >> $GITHUB_ENV

    - name: Setup Publish Directory Variable
      run: |
        echo "PUBLISH_DIR=${{ env.BASE_DIR }}/${{ env.PUBLISH_DIRNAME }}" >> $GITHUB_ENV
        echo "PUBLISH_RELATIVE_DIR_FROM_BASE=${{ env.PUBLISH_DIRNAME }}" >> $GITHUB_ENV

    - name: Setup Version Information Path Variable
      run: |
        echo "VERSION_INFO_PATH=${{ env.PUBLISH_DIR }}/VERSION.txt" >> $GITHUB_ENV

    #----------------------------------------------------------
    # Checkout repository
    #----------------------------------------------------------
    - name: Checkout
      uses: actions/checkout@v4

    #----------------------------------------------------------
    # Setup the application version
    #----------------------------------------------------------
    - name: "Setup the application version ('AssemblyVersion' tag in csproj)"
      if: ${{ inputs.version == '' }}
      run: |
          VERSION=$(grep '<AssemblyVersion>' ${{ env.CSPROJ_PATH }} | sed -E 's/.*<AssemblyVersion>([^<]+)<\/AssemblyVersion>.*/\1/')
          if [ "$VERSION" == "" ]; then
            VERSION="0.0.0"
            echo "::warning::Could not find AssemblyVersion tag in csproj file. Defaulting to ${VERSION}"
          fi
          echo "BUILD_VERSION=${VERSION}" >> $GITHUB_ENV

    - name: "Setup the application version (inputs.version)"
      if: ${{ inputs.version != '' }}
      run: |
        echo "::info::The version value will be overridden to '${{ inputs.version }}'"
        echo "BUILD_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

    #----------------------------------------------------------
    # Setup the artifact name
    #----------------------------------------------------------
    - name: Setup the artifact name
      run: |
        ARTIFACT_NAME="${{ env.PREFIX }}-${{ env.BUILD_CONFIGURATION }}-v${{ env.BUILD_VERSION }}-${{ inputs.channel }}" >> $GITHUB_ENV
        {
          echo "## Artifact Name"
          echo ""
          echo "${{ env.ARTIFACT_NAME }}"
        } >> $GITHUB_STEP_SUMMARY

    #----------------------------------------------------------
    # Show setup Environment Variables
    #----------------------------------------------------------
    - name: Show Environment Variables
      run: |
        {
          echo "## Environment Variables"
          echo ""
          echo "|name|value|"
          echo "|----|-----|"
          echo "|PREFIX|${{ env.PREFIX }}|"
          echo "|DOTNET_SDK_VERSION|${{ env.DOTNET_SDK_VERSION }}|"
          echo "|BASE_DIR|${{ env.BASE_DIR }}|"
          echo "|PUBLISH_DIR|${{ env.PUBLISH_DIR }}|"
          echo "|BUILD_CONFIGURATION|${{ env.BUILD_CONFIGURATION }}|"
          echo "|BUILD_VERSION|${{ env.BUILD_VERSION }}|"
          echo "|VERSION_INFO_PATH|${{ env.VERSION_INFO_PATH }}|"
          echo "|ARTIFACT_NAME|${{ env.ARTIFACT_NAME }}|"
          echo ""
        } >> $GITHUB_STEP_SUMMARY


    #----------------------------------------------------------
    # Setup .NET SDK
    #----------------------------------------------------------
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

    #----------------------------------------------------------
    # Build
    #----------------------------------------------------------
    - name: Build Language Server
      run: |
        pushd ${{ env.BASE_DIR }}
        dotnet publish -p:FileVersion=${{ env.BUILD_VERSION }} -p:Version=${{ env.BUILD_VERSION }} -p:AssemblyVersion=${{ env.BUILD_VERSION }} -c ${{ env.BUILD_CONFIGURATION }} -o ${{ env.PUBLISH_RELATIVE_DIR_FROM_BASE }}
        popd

    #----------------------------------------------------------
    # Create Version Information File
    #----------------------------------------------------------
    - name: Create Version information file
      run: |
        mkdir -p ${{ env.PUBLISH_DIR }}
        echo "Build channel: ${{ inputs.channel }}" > ${{ env.VERSION_INFO_PATH }}
        echo "Build date: $(date)" >> ${{ env.VERSION_INFO_PATH }}
        echo "Version: ${{ env.BUILD_VERSION }}" >> ${{ env.VERSION_INFO_PATH }}
        echo "Branch: ${{ github.ref_name }}" >> ${{ env.VERSION_INFO_PATH }}
        echo "Commit: ${{ github.sha }}" >> ${{ env.VERSION_INFO_PATH }}
        echo "Build Configuration: ${{ env.BUILD_CONFIGURATION }}" >> ${{ env.VERSION_INFO_PATH }}

    - name: Show Version information file
      run: |
        {
          if [ -f ${{ env.VERSION_INFO_PATH }} ]; then
            echo "## Version Information File"
            echo ""
            echo "\`\`\`"
            cat ${{ env.VERSION_INFO_PATH }}
            echo ""
            echo "\`\`\`"
          fi
        } >> $GITHUB_STEP_SUMMARY

    #----------------------------------------------------------
    # Create Artifact
    #----------------------------------------------------------
    - name: Create Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.BASE_DIR }}/${{ env.PUBLISH_DIRNAME }}
