name: Build Language Server (rc)

on:
  push:
    branches:
      - release/*

  workflow_dispatch:

jobs:
  build-language-server-rc:
    uses: ./.github/workflows/build_language_server.yml
    secrets: inherit
    with:
      channel: rc
