name: Build KSP Compiler (rc)

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build-compiler-rc:
    uses: ./.github/workflows/build_csproj.yml
    secrets: inherit
    with:
      channel: release
      prefix: KSP-Compiler
      base_dir: "Compiler/Features/Compilation/Applications/Compilation.Cli"
      csproject_filename: "Compilation.Cli.csproj"
